machine:
  services:
    - docker
  node:
    version: 7.6.0

version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: 
          name: truffle develop
          command: truffle develop
      - run:
          name: truffle tests
          command: npm run test