machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
  services:
    - docker
  node:
    version: 7.6.0

version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout

      # Node
      - run: npm install 
      - save_cache:
          key: node
          paths:
            - node_modules

      - run: sudo npm install truffle -g 


      - run: truffle develop
      - run:
          name: truffle tests
          command: npm run test